# The name of this app. Must be unique within a project.
name: nextjs

type: 'nodejs:14'

dependencies:
    nodejs:
        yarn: "1.22.17"
        pm2: "5.2.0"

build:
    flavor: none

variables:
    env:
        NODE_OPTIONS: --max-old-space-size=1536
        GENERATED_VARS: 'deploy/platformsh.environment'

size: L

resources:
    base_memory: 1024
    memory_ratio: 1024

hooks:
    build: |
        # Build dependencies.
        set -e
        #   a. For the main app.
        yarn --frozen-lockfile
        #   b. For our verification test.
        cd platformsh-scripts/test/next-drupal-debug
        yarn --frozen-lockfile
    post_deploy: |
        # Verify the connection to the backend can be made with those variables.
        cd platformsh-scripts/test/next-drupal-debug && yarn debug
        # Build the frontend.
        cd $PLATFORM_APP_DIR && yarn build

web:
    commands:
        start: |
            # Get the frontend app name, and start a daemon that watches for changes.
            APP=$(cat package.json | jq -r '.name')
            pm2 start npm --no-daemon --watch --name $APP --max-restarts 100 -- start -- -p $PORT
            # --max-restarts
            # --kill-timeout

disk: 512

mounts:
    /.cache:
        source: local
        source_path: 'cache'
    /.next:
        source: local
        source_path: 'next'
    /.pm2:
        source: local
        source_path: 'next'
    deploy:
        source: service
        service: files
        source_path: deploy
