# The name of this app. Must be unique within a project.
name: nextjs

type: 'nodejs:14'

variables:
  env: 
    GENERATED_VARS: 'deploy/platformsh.environment'

dependencies:
    nodejs:
        yarn: "1.22.17"
        pm2: "5.2.0"

build:
    flavor: none

variables:
    env:
        NODE_OPTIONS: --max-old-space-size=1536

size: L

resources:
    base_memory: 1024
    memory_ratio: 1024

hooks:
    build: !include
      type: string
      path: platformsh-scripts/hooks.build.sh
    post_deploy: !include
      type: string
      path: platformsh-scripts/hooks.post_deploy.sh

web:
    commands:
        start: !include
            type: string
            path: platformsh-scripts/web.commands.start.sh

disk: 512

mounts:
    /.cache:
        source: local
        source_path: 'cache'
    /.next:
        source: local
        source_path: 'next'
    /.pm2:
        source: local
        source_path: 'next'
    deploy:
        source: service
        service: files
        source_path: deploy
